import re
filepath = 'resources/views/it/inventory/index.blade.php'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Remove the incorrectly placed JS block
bad_js_start = content.find('function OLDtoggleAccordion')
if bad_js_start != -1:
    bad_js_end = content.find('</script>', bad_js_start)
    if bad_js_end != -1:
        # Just wipe it out (including the extra </script> we might have caused)
        # Actually, let's just find the exact text and replace it
        pass

# Let's just grab the whole script block we injected and remove it
match = re.search(r'function OLDtoggleAccordion.*?\}\n\n', content, re.DOTALL)
if match:
    content = content.replace(match.group(0), '')

# Now let's inject it into the CORRECT place: after "function openAddModal() {"
js_snippet = """
function toggleAccordion(prefix, index, total) {
  var body = document.getElementById('body_' + prefix + index);
  var header = document.getElementById('header_' + prefix + index);
  var icon = document.getElementById('icon_' + prefix + index);
  
  if (body.style.display === 'none') {
    body.style.display = 'block';
    icon.style.transform = 'rotate(180deg)';
    header.style.background = 'rgba(14, 165, 233, 0.05)';
    header.style.borderBottom = '1px solid #0ea5e9';
  } else {
    body.style.display = 'none';
    icon.style.transform = 'rotate(0deg)';
    header.style.background = '#f8fafc';
    header.style.borderBottom = '1px solid var(--border)';
  }
}

function nextAccordion(prefix, index, total) {
  var currentBody = document.getElementById('body_' + prefix + index);
  var currentHeader = document.getElementById('header_' + prefix + index);
  var currentIcon = document.getElementById('icon_' + prefix + index);
  if (currentBody) currentBody.style.display = 'none';
  if (currentIcon) currentIcon.style.transform = 'rotate(0deg)';
  if (currentHeader) {
      currentHeader.style.background = '#f8fafc';
      currentHeader.style.borderBottom = '1px solid var(--border)';
  }
  
  var nextIndex = index + 1;
  if (nextIndex < total) {
    var nextBody = document.getElementById('body_' + prefix + nextIndex);
    var nextHeader = document.getElementById('header_' + prefix + nextIndex);
    var nextIcon = document.getElementById('icon_' + prefix + nextIndex);
    if (nextBody) nextBody.style.display = 'block';
    if (nextIcon) nextIcon.style.transform = 'rotate(180deg)';
    if (nextHeader) {
        nextHeader.style.background = 'rgba(14, 165, 233, 0.05)';
        nextHeader.style.borderBottom = '1px solid #0ea5e9';
        nextHeader.scrollIntoView({behavior: 'smooth', block: 'start'});
    }
  }
}
"""

if 'function toggleAccordion(' not in content:
    idx = content.find('function openAddModal() {')
    if idx != -1:
        content = content[:idx] + js_snippet + '\n' + content[idx:]


# Finally, fix the literal `\n` in the HTML grid.
# The `\n` was placed right after `</div>` for every field generated by `reformat_forms.py`.
# E.g. `</div>\n` literally. Wait, earlier I did:
# `html += "              " + field(...) + "\\n"`
# So it is literal backslash-n.
content = content.replace('</div>\\n', '</div>\n')

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
